SET search_path TO public;

INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CNY', '¥', 'Renminbi', false, 1);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('VND', '₫', 'Vietnamese đồng', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AED', 'AED', 'United Arab Emirates dirham', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AFN', '؋', 'Afghan afghani', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ALL', 'L', 'Albanian lek', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AMD', '֏', 'Armenian dram', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AOA', 'Kz', 'Angolan kwanza', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ARS', '$', 'Argentine peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AUD', '$', 'Australian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AWG', 'ƒ', 'Aruban florin', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('AZN', '₼', 'Azerbaijani manat', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BAM', 'KM', 'Bosnia and Herzegovina convertible mark', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BBD', '$', 'Barbadian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BDT', '৳', 'Bangladeshi taka', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BGN', 'lv.', 'Bulgarian lev', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BIF', 'FBu', 'Burundian franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BMD', '$', 'Bermudian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BND', '$', 'Brunei dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BOB', 'Bs', 'Bolivian boliviano', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BRL', 'R$', 'Brazilian real', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BSD', '$', 'Bahamian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BTN', 'Nu', 'Bhutanese ngultrum[F]', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BWP', 'P', 'Botswana pula', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BYN', 'Br', 'Belarusian ruble', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BZD', '$', 'Belize dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CAD', '$', 'Canadian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CDF', 'FC', 'Congolese franc', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CHF', 'Fr', 'Swiss franc', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CLP', '$', 'Chilean peso', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('COP', '$', 'Colombian peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CRC', '₡', 'Costa Rican colón', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CUP', '$', 'Cuban peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CVE', 'CVE', 'Cape Verdean escudo', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('CZK', 'Kč', 'Czech koruna', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('DJF', 'Fdj', 'Djiboutian franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('DKK', 'kr', 'Danish krone', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('DOP', '$', 'Dominican peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('DZD', 'DA', 'Algerian dinar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('EGP', 'LE', 'Egyptian pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ERN', 'Nkf', 'Eritrean nakfa', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ETB', 'Br', 'Ethiopian birr', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('EUR', '€', 'Euro', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('FJD', '$', 'Fijian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('FKP', '£', 'Falkland Islands pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GBP', '£', 'Sterling', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GEL', '₾', 'Georgian lari', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GHS', '₵', 'Ghanaian cedi', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GIP', '£', 'Gibraltar pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GMD', 'D', 'Gambian dalasi', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GNF', 'Fr', 'Guinean franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GTQ', 'Q', 'Guatemalan quetzal', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('GYD', '$', 'Guyanese dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('HKD', '$', 'Hong Kong dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('HNL', 'L', 'Honduran lempira', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('HTG', 'G', 'Haitian gourde', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('HUF', 'Ft', 'Hungarian forint', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('IDR', 'Rp', 'Indonesian rupiah', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ILS', '₪', 'Israeli new shekel', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('INR', '₹', 'Indian rupee', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('IRR', 'Rl', 'Iranian rial', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ISK', 'kr', 'Icelandic króna', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('JMD', '$', 'Jamaican dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('JOD', 'JD', 'Jordanian dinar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('JPY', '¥', 'Japanese yen', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KES', 'Sh', 'Kenyan shilling', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KGS', '⃀', 'Kyrgyz som', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KHR', '៛', 'Cambodian riel', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KMF', 'FC', 'Comorian franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KPW', '₩', 'North Korean won', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KRW', '₩', 'South Korean won', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KYD', '$', 'Cayman Islands dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KZT', '₸', 'Kazakhstani tenge', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('LAK', '₭', 'Lao kip', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('LBP', 'LL', 'Lebanese pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('LKR', 'Rs', 'Sri Lankan rupee', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('LRD', '$', 'Liberian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('LSL', 'L', 'Lesotho loti', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MAD', 'DH', 'Moroccan dirham', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MDL', 'L', 'Moldovan leu', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MKD', 'DEN', 'Macedonian denar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MMK', 'K', 'Burmese kyat', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MNT', '₮', 'Mongolian tögrög', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MOP', 'MOP$', 'Macanese pataca', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MUR', 'Rs', 'Mauritian rupee', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MVR', 'Rf', 'Maldivian rufiyaa', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MWK', 'K', 'Malawian kwacha', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MXN', '$', 'Mexican peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MYR', 'RM', 'Malaysian ringgit', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MZN', 'Mt', 'Mozambican metical', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('NAD', '$', 'Namibian dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('NGN', '₦', 'Nigerian naira', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('NIO', 'C$', 'Nicaraguan córdoba', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('NOK', 'kr', 'Norwegian krone', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('NPR', 'रु', 'Nepalese rupee', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('NZD', '$', 'New Zealand dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PAB', 'B/', 'Panamanian balboa', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PEN', 'S/', 'Peruvian sol', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PGK', 'K', 'Papua New Guinean kina', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PHP', '₱', 'Philippine peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PKR', 'Rs', 'Pakistani rupee', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PLN', 'zł', 'Polish złoty', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('PYG', '₲', 'Paraguayan guaraní', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('QAR', 'QR', 'Qatari riyal', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('RON', 'L', 'Romanian leu', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('RSD', 'DIN', 'Serbian dinar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('RUB', '₽', 'Russian ruble', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('RWF', 'FRw', 'Rwandan franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SAR', 'SAR', 'Saudi riyal', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SBD', '$', 'Solomon Islands dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SCR', 'Rs', 'Seychellois rupee', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SDG', 'LS', 'Sudanese pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SEK', 'kr', 'Swedish krona', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SGD', '$', 'Singapore dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SHP', '£', 'Saint Helena pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SLE', 'Le', 'Sierra Leonean leone', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SOS', 'Sh', 'Somali shilling', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SRD', '$', 'Surinamese dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SSP', 'SS£', 'South Sudanese pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('STN', 'Db', 'São Tomé and Príncipe dobra', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SYP', 'LS', 'Syrian pound', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('SZL', 'L', 'Swazi lilangeni', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('THB', '฿', 'Thai baht', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TJS', 'SM', 'Tajikistani somoni', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TMT', 'm', 'Turkmenistani manat', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TOP', 'T$', 'Tongan paʻanga[O]', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TRY', '₺', 'Turkish lira', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TTD', '$', 'Trinidad and Tobago dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TWD', '$', 'New Taiwan dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TZS', 'Sh', 'Tanzanian shilling', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('UAH', '₴', 'Ukrainian hryvnia', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('USD', '$', 'United States dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('UYU', '$', 'Uruguayan peso', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('UZS', 'Sʻ', 'Uzbekistani sum', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('VED', 'Bs.D', 'Venezuelan digital bolívar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('VES', 'Bs.S', 'Venezuelan sovereign bolívar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('VUV', 'VT', 'Vanuatu vatu', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('WST', '$', 'Samoan tālā', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('XAF', 'F.CFA', 'Central African CFA franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('XCD', 'EC$', 'Eastern Caribbean dollar', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('XCG', 'Cg', 'Caribbean guilder', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('XOF', 'F.CFA', 'West African CFA franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('XPF', '₣', 'CFP franc', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('YER', 'Rl', 'Yemeni rial', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ZAR', 'R', 'South African rand', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ZMW', 'K', 'Zambian kwacha', false, 2);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('BHD', 'BD', 'Bahraini dinar', false, 3);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('IQD', 'ID', 'Iraqi dinar', false, 3);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('KWD', 'KD', 'Kuwaiti dinar', false, 3);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('LYD', 'LD', 'Libyan dinar', false, 3);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('OMR', 'RO', 'Omani rial', false, 3);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('TND', 'DT', 'Tunisian dinar', false, 3);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MGA', 'Ar', 'Malagasy ariary', false, 1);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('MRU', 'UM', 'Mauritanian ouguiya', false, 1);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('UGX', 'Sh', 'Ugandan shilling', false, 0);
INSERT INTO currencies (code, symbol, currency_name, is_deleted, precision) VALUES ('ZWG', 'ZiG', 'Zimbabwe gold', false, 2);
